api:
  dashboard: true
  insecure: true 
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: esteban-felipe-network
    watch: true

log:
  level: "DEBUG"  # Log de depuración detallada para diagnóstico.

accessLog: {}  # Activa los logs de acceso.
