name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar clave SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > server_key
        chmod 600 server_key

    - name: Deploy al servidor
      run: |
        ssh -i server_key -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /ruta/del/proyecto
          git pull origin main
          docker-compose up -d --build
        EOF